name: Deploy to WordPress.org (Manual)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or Tag to Deploy (e.g. main or v1.4.8.3)'
        required: true
        default: 'main'

jobs:
  deploy-wporg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Deploy to WordPress.org SVN
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: notify-with-gowa
